### PR TITLE
Hide Submit Late Entry from dropped player

### LINKED ISSUE #24: "Submit late entry" link should not be visible to dropped player
**Describe the bug**
A dropped player able see and click the "Submit late entry" link of the event that they have dropped out of

**To Reproduce**
1. Join an event with (for example) late entry limit set to 3
2. Drop on round 1
3. When round 2 started, the dropped player will see "Submit Late Entry" next to the active event name in Player CP
4. When you click on it, it will ask you to enter new deck
5. Once you enter a new deck, the db won't undrop the player but it will change their registered deck to the newly-inputted deck

**Expected behavior**
A dropped player should not be able see the "Submit late entry" link

### PR DESCRIPTION
**Pull request by stash86**
fixes #24

### CODE REVIEW

File: gatherling/models/Entry.php [hunk 1]
```diff
@@ -57,6 +57,24 @@ public static function getActivePlayers($eventid)
...
 
+    public static function playerRegistered($eventid, $playername)
+    {
+        $db = Database::getConnection();
+        $stmt = $db->prepare('SELECT e.player
+            FROM entries e
+            JOIN events ev ON e.event_id = ev.id
+            WHERE e.event_id = ?
+            AND e.player = ?
+            GROUP BY player');
```
Comment (silasary) [inline gatherling/models/Entry.php:68]: Queries should use `entries n, events e`

**Review by silasary — CHANGES_REQUESTED** [review]

**Comment by stash86** [comment]
change made

**Review by silasary — APPROVED** [review]
